# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-greenhouse"
BBFILE_PATTERN_meta-greenhouse = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-greenhouse = "6"

LAYERDEPENDS_meta-greenhouse = "core"
LAYERSERIES_COMPAT_meta-greenhouse = "scarthgap"
